name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux
          - { cabal: "3.2", os: ubuntu-latest,  ghc: "7.10.3" }
          - { cabal: "3.2", os: ubuntu-latest,  ghc: "8.0.2"  }
          - { cabal: "3.2", os: ubuntu-latest,  ghc: "8.2.2"  }
          - { cabal: "3.2", os: ubuntu-latest,  ghc: "8.4.4"  }
          - { cabal: "3.2", os: ubuntu-latest,  ghc: "8.6.5"  }
          - { cabal: "3.2", os: ubuntu-latest,  ghc: "8.8.4"  }
          - { cabal: "3.4", os: ubuntu-latest,  ghc: "8.10.7" }
          - { cabal: "3.4", os: ubuntu-latest,  ghc: "9.0.1"  }
          # Win
          - { cabal: "3.2", os: windows-latest, ghc: "8.4.4"  }
          - { cabal: "3.2", os: windows-latest, ghc: "8.6.5"  }
          # OOM when building tests
          # - { cabal: "3.4", os: windows-latest, ghc: "8.8.4"  }
          # - { cabal: "3.4", os: windows-latest, ghc: "8.10.4" }
          # Too flaky:
          # - { cabal: "3.4", os: windows-latest,  ghc: "9.0.1"  }
          # MacOS
          - { cabal: "3.2", os: macOS-latest,   ghc: "8.4.4"  }
          - { cabal: "3.2", os: macOS-latest,   ghc: "8.6.5"  }
          - { cabal: "3.2", os: macOS-latest,   ghc: "8.8.4"  }
          - { cabal: "3.2", os: macOS-latest,   ghc: "8.10.7" }
          - { cabal: "3.4", os: macOS-latest,   ghc: "9.0.1"  }
      fail-fast: false

    steps:
    # ----------------
    - uses: actions/checkout@v2
    # ----------------
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    # ----------------
    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}--${{ github.Shah }}-CACHE_V3
    # ----------------
    - name: Versions
      run: |
        cabal -V
        ghc -V
    # ----------------
    - name: Make sdist
      run: |
        ls -laF
        mkdir sdist
        cabal sdist -o sdist
    - name: Unpack
      run: |
        mkdir unpacked
        tar -C unpacked -xzf sdist/vector*tar.gz
        cd unpacked
    # ----------------
    - name: cabal check
      run: |
        cabal -vnormal check
    # ----------------
    # GHC 7.10 fails with PIE-related linker errors. Thus it needs extra
    # encouragement for linker in form of flags.
    - name: Build
      run: |
        if [ ${{matrix.ghc}} = 7.10.3 ]; then
          EXTRA_FLAGS=--ghc-option="-optl-no-pie"
        fi
        echo $EXTRA_FLAGS
        cabal $EXTRA_FLAGS configure --haddock-all --enable-tests --enable-benchmarks --benchmark-option=-l
        cabal $EXTRA_FLAGS build all --write-ghc-environment-files=always
    # ----------------
    - name: Test
      run: |
        cabal test all
